"""Paths, names and the closed grammar of the canon module — the only place this module builds a path.

It imports nothing from any module and needs nothing installed: the standard library reads the sheet and
writes the documents. The sheet is the one source of every Skill and of the glossary; this file says where
the sheet is, where a Skill of a tab's family may lie in the tree, and how a generated file is told from a hand-written
one. It names no module: a tab is found by its family, so a new module is rows of the sheet and nothing here. The tools
run on the host over the tree this package sits in, its root one level up.
"""

from __future__ import annotations

from pathlib import Path

TREE_ROOT_DIR = Path(__file__).resolve().parent.parent
SKILLS_SHEET_PATH = TREE_ROOT_DIR / "module_skills" / "skills_sheet.xlsx"
GLOSSARY_SKILL_PATH = "module_skills/glossary.md"   # the one Skill the glossary is rendered into

# the tables the sheet holds, each told by its header, wherever it lies
RULE_HEADER = ("skill_path", "rule_type_id", "rule_id", "description", "scope", "expected_form", "exception")
SKILL_REGISTER_HEADER = ("sheet_tab", "skill_path", "summary")
GLOSSARY_HEADER = ("section", "concept", "code", "artifact_key", "ui_label", "never", "holds", "why_twice", "external_vocabulary")
RULE_TYPE_ID_HEADER = ("rule_type_id",)
FILES_MATRIX_HEADER = ("path",)   # then one column per Skill, headed by the stem of its skill_path
SKILL_MARK = "X"

# what skills-configurables reads in a controlled config.py: the block of an operator's records, by its one name, and
# the nine fields every record carries, in the order its table shows them
CONFIGURABLES_NAME = "CONFIGURABLES"
CONFIGURABLE_FIELDS = ("name", "class", "value", "unit", "meaning", "tui", "experiment_identity", "requires_rerun",
                       "risk")

# the first line of every file skills-sync writes — what tells a generated document from a hand-written one, and
# what the sync deletes by when a Skill leaves the sheet
GENERATED_MARKER = "<!-- generated by skills-sync from skills_sheet.xlsx — edit the sheet, not this file -->"


def skill_document_path(skill_path: str) -> Path:
    return TREE_ROOT_DIR / skill_path


def skill_places(sheet_tab: str) -> tuple[str, ...]:
    """Where a Skill of a tab's family may lie, relative to the root of the tree: the canon's in `module_skills/`, its
    glossary among them, and beside each of its sub-modules; a module's in its `skills/` and beside each of its
    sub-modules. A tab of no family has no place, and the sheet reader refuses it."""
    if sheet_tab == "module_skills":
        return ("module_skills/skill_*.md", GLOSSARY_SKILL_PATH, "module_skills/sub_module_*/skill_*.md")
    if sheet_tab.startswith("module_"):
        return (f"{sheet_tab}/skills/skill_*.md", f"{sheet_tab}/sub_module_*/skill_*.md")
    return ()
